feat: patterns highlighting
zifeo/whiz pull request #117
Opened 2024-01-31 15:10 UTC by destifo

### **This is a draft pull request, it's not final.**

The highlighting is done by the **tailspin** crate.

<img width="1470" alt="Screenshot 2024-01-31 at 12 53 45 PM" src="https://github.com/zifeo/whiz/assets/77430541/76442476-401f-4c43-a2d8-72b2e82df8fe">
<img width="1470" alt="Screenshot 2024-01-31 at 12 53 56 PM" src="https://github.com/zifeo/whiz/assets/77430541/077940ab-1321-4061-b48b-75e047bd64fc">
<img width="1470" alt="Screenshot 2024-01-31 at 12 54 03 PM" src="https://github.com/zifeo/whiz/assets/77430541/b1f3633c-afef-4f7a-bcd6-efc2de4b4a9a">
<img width="1470" alt="Screenshot 2024-01-31 at 12 54 08 PM" src="https://github.com/zifeo/whiz/assets/77430541/593b3ec4-e012-4fec-a815-283a5e10052f">
<img width="1470" alt="Screenshot 2024-01-31 at 12 54 12 PM" src="https://github.com/zifeo/whiz/assets/77430541/692a3ed1-2e53-47d7-9f4b-931c8e38351b">
<img width="1470" alt="Screenshot 2024-01-31 at 12 54 15 PM" src="https://github.com/zifeo/whiz/assets/77430541/69666f2f-d27b-4f56-9a19-8c4420d188b9">
<img width="1470" alt="Screenshot 2024-01-31 at 12 54 19 PM" src="https://github.com/zifeo/whiz/assets/77430541/d4075cc6-8805-462d-ae5d-461baca898a0">
<img width="1470" alt="Screenshot 2024-01-31 at 12 54 23 PM" src="https://github.com/zifeo/whiz/assets/77430541/80eed0c6-51e0-4445-b00b-01ed4021c7a6">
<img width="1470" alt="Screenshot 2024-01-31 at 12 54 27 PM" src="https://github.com/zifeo/whiz/assets/77430541/0d4531fa-6a66-4a11-9d5b-8554da3c6822">

2024-02-01 20:09 UTC, zifeo requested changes

2024-02-01 20:09 UTC, zifeo commented on src/actors/command.rs
> +        let mut tspin_p = Exec::cmd("tspin")
as tailspin is a rust library, do you see a way to re-use the functionality [directly](https://github.com/bensadeh/tailspin/blob/main/src/main.rs)? otherwise people have to install it manually and the process to process communicate will be anyway slower than a direct integration.

2024-02-02 07:09 UTC, destifo commented on src/actors/command.rs
> +        let mut tspin_p = Exec::cmd("tspin")
Ok, I see. I guess you are right, installing manually will be a hustle. I will start looking into direct integration. I wasn't able to import the library in project but I will try to do that again cause copying the code directly will not be ideal as we would have to manually update the code when tailspin releases new versions. I will try the different options in hand.

2024-02-02 12:33 UTC, zifeo commented on src/actors/command.rs
> +        let mut tspin_p = Exec::cmd("tspin")
Indeed, using cargo git import you should be able to link as a module and import the required elements (they seem public which is good news).

2024-02-02 15:16 UTC, destifo commented on src/actors/command.rs
> +        let mut tspin_p = Exec::cmd("tspin")
Yeah, and I imported the library using cargo git import and it looks like the cargo.toml file in the tailspin project doesn't have the [lib] section, only has [[bin]] as a binary crate and I can't import it within the whiz project. Should I edit the tailspin project I forked and make it a library crate so we can use it?

2024-02-02 16:20 UTC, zifeo commented on src/actors/command.rs
> +        let mut tspin_p = Exec::cmd("tspin")
@destifo definitely something you can do and contribute back with a PR 👍 hopefully the maintainer will see the usage

2024-02-02 16:28 UTC, destifo commented on src/actors/command.rs
> +        let mut tspin_p = Exec::cmd("tspin")
Great, I will work on this.

2024-02-02 20:53 UTC, destifo commented on src/actors/command.rs
> +        let mut tspin_p = Exec::cmd("tspin")
I have completed adding the highlighting feature directly from the library and it worked. I applied the highlighting on the output from the process in the command actor. 


<img width="1470" alt="Screenshot 2024-02-02 at 11 37 42 PM" src="https://github.com/zifeo/whiz/assets/77430541/cfa49b69-b05f-45bf-bdc3-3dc7447ec4bc">
<img width="1470" alt="Screenshot 2024-02-02 at 11 38 47 PM" src="https://github.com/zifeo/whiz/assets/77430541/92516d23-35bd-4686-8931-9addb3aa118f">
<img width="1470" alt="Screenshot 2024-02-02 at 11 38 52 PM" src="https://github.com/zifeo/whiz/assets/77430541/e6c1895b-ac79-467c-bf5b-2439e3b5ac41">
<img width="1470" alt="Screenshot 2024-02-02 at 11 38 57 PM" src="https://github.com/zifeo/whiz/assets/77430541/258538f4-40cd-43b3-9af3-304a0e1ad15d">
<img width="1470" alt="Screenshot 2024-02-02 at 11 39 04 PM" src="https://github.com/zifeo/whiz/assets/77430541/2a7569da-e2d3-4ec4-8977-08c58e817503">
<img width="1470" alt="Screenshot 2024-02-02 at 11 37 39 PM" src="https://github.com/zifeo/whiz/assets/77430541/3dbc97d1-b542-4f6b-abd1-21aa0ef59f51">
<img width="1470" alt="Screenshot 2024-02-02 at 11 39 08 PM" src="https://github.com/zifeo/whiz/assets/77430541/aa0365b1-88d6-4afe-9ed2-f5350e9701a8">

2024-02-03 12:54 UTC, zifeo reviewed
Lgtm, can you link the pull request upstream (we will wait on the maintainer answer before merging)?

2024-02-03 12:54 UTC, zifeo commented on src/actors/custom_highlighter.rs
> +    theme::{self, processed::Theme},
we usually keep all files in the actors folder as actor, maybe this file can be moved elsewhere?

2024-02-03 19:04 UTC, destifo commented on src/actors/custom_highlighter.rs
> +    theme::{self, processed::Theme},
Ok, that makes sense. I will move it to the **utils** module and update my branch.

2024-02-03 19:06 UTC, destifo commented
Yeah, I will send the PR to the tailspin repo and wait reply from the maintainers.

2024-02-03 20:03 UTC, destifo commented
I have raised the PR for the tailspin repo [here](https://github.com/bensadeh/tailspin/pull/116).

2024-02-04 10:12 UTC, destifo commented
I have moved the code to utils file, but I think it's better to move the utils.rs to a new folder and place the highlighter code to separate file which will be under the utils module. I didn't do that cause I didn't wanna change that much of the codebase, but if it's ok, I will.

2024-02-04 12:04 UTC, zifeo commented
@destifo go 👍

2024-02-05 07:12 UTC, destifo commented
I have reorganized the util files under one directory. We will only modify the custom_highlighter when there are changes related to the highlighting in the future.

2024-10-12 15:43 UTC, zifeo commented
@destifo wanna terminate that one? seems now possible with https://github.com/bensadeh/tailspin/issues/118#issuecomment-2408572029

2024-10-13 17:26 UTC, destifo commented
Ok, I will update accordingly.

2025-11-13 21:49 UTC, closed without merging