feat(options): add `log` job option
zifeo/whiz pull request #16
Opened 2023-01-13 21:47 UTC by msga-mmm

Add `log` job option which allows to save the output of a job in a given array of file paths under the `logs` folder at the project root path.

A matrix of file paths is accepted instead of a single path to allow `backups` or `compound` logs, e.g. the following example configuration has two jobs with independent logs but also with a shared log file.

```yaml
watch_parent:
    workdir: src
    shell: ls
    watches:
        - "*"
        - "../*"
    log: changed_files.txt

watch_src:
    workdir: src
    shell: ls
    watches: "*"
    log: 
      - changed_files.txt
      - changed_src_files.txt
```

2023-01-14 12:38 UTC, zifeo reviewed
Nice WIP

2023-01-14 12:38 UTC, zifeo commented on src/actors/console.rs
> +        if let Some(log_folder) = Path::new(log_file).parent() {
I would move this in the constructor or setup steps to avoid running on the condition on every message, maybe even to the "file" in the same step and only write when there is a message.

2023-01-14 12:38 UTC, zifeo commented on src/config.rs
> +    pub log: Lift<String>,
I would go one feature ahead: allow to match the output via regex directly to one of the channel (/dev/stdout → whiz output, /dev/stderr → whiz output in red, /dev/null → ignored, any other file become your login files). 

```
pipes:
  "^[app]": /dev/stdout
  "^.*(ERROR|error).*$": /dev/stderr
  "TRACE": /dev/null
  "http://(.*)": "./logs/$1/requests.log"
```

If the file does not exists, we would have per default:

```
pipes:
  ".*": /dev/stdout
```

2023-01-14 12:46 UTC, zifeo commented on src/config.rs
> +    pub log: Lift<String>,
Too early to be implemented but this would allow a very nice trick:

```
pipes
  "accept": /dev/stdin#yes
```

2023-01-15 01:55 UTC, zifeo commented on src/config.rs
> +    pub log: Lift<String>,
Re-thinking about that, we should leave the colors for another task and embrace of the URL syntax for virtual tabs. The following example will create two more tabs (named virtual_views and virtual_views_error), silence everything that contains "TRACE" and create a log file for the lines matching that regex.

```
pipes: // no regex match go to whiz://[task_name] as default
  "^[app]": whiz://virtual_views
  "^.*(ERROR|error).*$": whiz://virtual_views_error
  "TRACE": /dev/null // no output, file://dev/null should also be valid
  "http://(.*)": "./logs/$1/requests.log"
```

2023-01-15 22:58 UTC, msga-mmm commented on src/actors/console.rs
> +        if let Some(log_folder) = Path::new(log_file).parent() {
I didn't understand too much the last sentence:

> maybe even to the "file" in the same step and only write when there is a message.

I moved the folder creation when parsing the paths of the log files, in that way it only runs once on initialization, however I don't know if that is what you meant.

2023-01-16 00:01 UTC, zifeo commented on src/actors/console.rs
> +        if let Some(log_folder) = Path::new(log_file).parent() {
@msga-mmm I meant your variable "file" below, e.g. you build the `File` at initialization and then only `file.write_all` in this frequently called function.

2023-01-19 09:02 UTC, zifeo commented on src/actors/command.rs
> +    pub fn from_str(redirection_uri: &str) -> Self {
Maybe https://docs.rs/url/latest/url/ is faster/handle more edge case?

2023-01-19 09:03 UTC, zifeo commented on src/main.rs
>          }
we will have to valide that pipes are valid in the config file in the main

2023-01-20 13:48 UTC, msga-mmm commented on src/actors/command.rs
> +    pub fn from_str(redirection_uri: &str) -> Self {
Suggestion implemented.

I didn't measure the performance of `url` crate, however I think the code looks easier to read than with the handcrafted implementation.

2023-01-20 17:45 UTC, msga-mmm commented on src/main.rs
>          }
Suggestion implemented.

Pipes are now parsed on initialization.

2023-01-20 18:01 UTC, msga-mmm commented on src/config.rs
> +    pub log: Lift<String>,
Suggestion implemented. Thanks for the feedback.

2023-01-20 19:11 UTC, zifeo reviewed
Nice!

2023-01-20 19:11 UTC, zifeo commented on src/actors/command.rs
> +    pipes: HashMap<String, Vec<Pipe>>,
Can we simplify to Vec<Pipe> or is there a need to send all pipes to all command actors?

2023-01-20 19:11 UTC, zifeo commented on src/actors/command.rs
> +                    continue 'output;
Can we rewrite without the label/continue, I believe it would be easier to understand?

2023-01-20 21:23 UTC, zifeo commented on src/main.rs
>          let console =
you may need to create some console actor for the tab that would have been not known or used by other task

2023-01-23 12:35 UTC, msga-mmm commented on src/config.rs
> +    #[serde(default)]
Done :heavy_check_mark:

2023-01-23 12:35 UTC, msga-mmm commented on src/actors/command.rs
> +    pipes: HashMap<String, Vec<Pipe>>,
Done :heavy_check_mark:

2023-01-23 13:07 UTC, msga-mmm commented on src/config.rs
> +                let redirection = OutputRedirection::from_str(redirection)?;
Done :heavy_check_mark:

2023-01-24 21:58 UTC, msga-mmm commented on src/actors/watcher.rs
> +        self.ignore.insert(path);
On my local tests the behavior works well, the log files are ignored.

To ignore a file there are two ways:

- Git Ignorer: this must be rebuilt on new changes as you mentioned.
- Ignore (task option): this is checked on each new WatchEvent. https://github.com/zifeo/whiz/blob/057e5c275726f6a12c2ea6afb7438b4c9bd3a0fd/src/actors/watcher.rs#L97-L101

The latter is useful is we can add dynamically new files to ignore, however I created a new field of `ignores` that is a list of files that will be ignored, the difference is that this list is the exact path rather than a glob.

2023-01-24 22:00 UTC, msga-mmm commented on src/actors/watcher.rs
> +        self.ignore.insert(path);
I have tried to add tests to make sure the behavior is always as desired, however I have not been able to figure out how to mock the actors correctly, so I will leave testing for a future pull request.

2023-01-24 23:05 UTC, msga-mmm commented on src/main.rs
>          let console =
I thought there was always only one console actor at all times, as the console actor is the front-end and how the user interacts with the application.

So I don't quite understand why create a new console actor, could you please elaborate on the reason for having two console actors and what the second one is expected to handle?

2023-01-24 23:08 UTC, msga-mmm commented on src/main.rs
>          let console =
A vague idea I have with what you possibly mean is about having two windows one with the normal task tabs, the ones created with `whiz://{task_name}`. And another window to view the virtual tabs, the tabs created from pipes.

2023-02-01 16:14 UTC, zifeo commented on src/main.rs
>          let console =
I meant what if whiz://new-tab-that-doesnt-exist-yet is used? The console actor needs to already create those tabs.

2023-02-01 16:15 UTC, zifeo requested changes
One last change and we should be good.

2023-02-02 15:04 UTC, msga-mmm commented on src/main.rs
>          let console =
For the creation of virtual tabs I have these lines:

```rust
for pipe in &self.pipes {
    if let OutputRedirection::Tab(name) = &pipe.redirection {
        self.console.do_send(RegisterPanel {
            name: name.to_owned(),
            addr: addr.clone(),
        });
    }
}
```


I still don't understand well what you mean, could you please give me an example config for pipes, so I can use it as a test to see what I am missing?

2023-02-02 15:09 UTC, msga-mmm commented on src/main.rs
>          let console =
This is how they look:

![whiz-pipes-example](https://user-images.githubusercontent.com/109926431/216362051-78bc1a13-9c2a-4f62-9cd7-351dfab5c605.png)

2023-02-02 15:42 UTC, zifeo commented
@msga-mmm Great! Can you resolve the conflict so I can approve it?

2023-02-02 15:42 UTC, zifeo approved these changes

2023-02-02 16:14 UTC, msga-mmm commented
> @msga-mmm Great! Can you resolve the conflict so I can approve it?

Done :heavy_check_mark: 

I have also added support for dynamic naming for virtual tabs in case it might be useful.

2023-02-02 20:43 UTC, merged