Use clap subcommands to run single task with arguments (#27)
zifeo/whiz pull request #43
Opened 2023-03-10 09:33 UTC by dmitryvm1

2023-03-11 14:49 UTC, zifeo requested changes
Great! I left some comments.

2023-03-11 14:49 UTC, zifeo commented on src/subcommands.rs
> +    External(Vec<OsString>),
Is there any advantage to use OsString instead of String here?

2023-03-11 14:49 UTC, zifeo commented on src/actors/command.rs
> +            Exec::cmd("cmd").args(&["/c", shell_arguments]);
Duplicate /c here

2023-03-11 14:49 UTC, zifeo commented on src/config.rs
> +impl<T: std::clone::Clone> From<Vec<T>> for Lift<T> {
👍

2023-03-11 14:49 UTC, zifeo commented on src/config.rs
> +    pub arguments: Lift<String>,
Can you add a comment and/or a usage example in whiz.yml?

2023-03-11 14:49 UTC, zifeo commented on src/config.rs
> +pub struct BoolTrueByDefault(pub bool);
I feel using a default function `#[serde(default="default_to_true")]` would be cleaner than wrapping the type.

2023-03-12 13:48 UTC, dmitryvm1 commented on src/subcommands.rs
> +    External(Vec<OsString>),
Thank you for bringing this to my attention.
There are no advantages to use OsString type here because it is cheaply inter-convertible with the String type. I will correct the type to String.

2023-03-13 20:08 UTC, dmitryvm1 commented on src/actors/command.rs
> +            Exec::cmd("cmd").args(&["/c", shell_arguments]);
fixed #[cd6a813](https://github.com/zifeo/whiz/pull/43/commits/cd6a81360b09b4481ab4cd0b39ecb5f79a2c2eaa)

2023-03-13 20:08 UTC, dmitryvm1 commented on src/subcommands.rs
> +    External(Vec<OsString>),
Done #[52d735f](https://github.com/zifeo/whiz/pull/43/commits/52d735fbe933ecaf9612024633111c76849c7f64)

2023-03-13 20:17 UTC, dmitryvm1 commented on src/config.rs
> +pub struct BoolTrueByDefault(pub bool);
Done  [fbbe9ff](https://github.com/zifeo/whiz/pull/43/commits/fbbe9ff8954b2421e6fadb67900652d3d3027c67)

2023-03-13 21:35 UTC, zifeo commented on src/config.rs
> +    pub arguments: Lift<String>,
@dmitryvm1 Can you explicit with `arguments` is needed over command?

2023-03-14 08:15 UTC, Natoandro commented on src/main.rs
> +                    let task_name = arguments[0].clone();
`arguments` could be empty...

2023-03-14 08:15 UTC, Natoandro commented on src/main.rs
> +                if args.run.is_empty() {
Return an error if `args.run` is empty? It should be incompatible with external...

2023-04-03 22:27 UTC, zifeo commented
@dmitryvm1 Are you interested in terminating this PR?

2023-04-05 11:37 UTC, closed without merging