Feature entrypoint per task
zifeo/whiz pull request #86
Opened 2023-07-18 13:22 UTC by 0xdeadbad

Pull request for  _Add ability to customise the entrypoint_ #22

2023-07-18 13:55 UTC, zifeo requested changes
Nice contrib, two comments before we move forward.

2023-07-18 13:55 UTC, zifeo commented on src/actors/command.rs
>          let exec = Exec::cmd("cmd").args(&["/c", args]);
How to enable this on Windows also?

2023-07-18 14:12 UTC, 0xdeadbad commented on src/actors/command.rs
>          let exec = Exec::cmd("cmd").args(&["/c", args]);
The same applies as for most Unix if I'm not wrong, Rust std should abstract this. Anyway I'll write it and test on a VM.

2023-07-18 14:22 UTC, 0xdeadbad commented on src/actors/command.rs
> +            if entrypoint.contains(' ') {
Not splitting the entire string, otherwise it will see two strings in the "Hello World". I'll use only split the first space and use it as the command, the rest can be a whole string and the entrypoint command itself should deal with it properly.

2023-07-18 14:33 UTC, zifeo commented on src/actors/command.rs
> +            if entrypoint.contains(' ') {
I can also give you another one:
```
  entrypoint: "ls  a b"
```
You may find some way to solve it around with external [crates](https://github.com/comex/rust-shlex).

2023-07-19 23:44 UTC, 0xdeadbad commented on src/actors/command.rs
> +            if entrypoint.contains(' ') {
Did the changes, I'll be working on polishing it. Also that crate is old, doesn't looks like very flexible, took a look at the source code to figure things out. Perhaps I can contrib to that crate too...

2023-07-20 08:27 UTC, zifeo reviewed
Looks great, one little suggestion

2023-07-20 08:27 UTC, zifeo commented on src/actors/command.rs
> +                Some(a) => { let a = a.clone(); if a.len() == 0 {} else { nargs.push(a) } },
.into_iter().filter().collect()?

2023-07-21 03:23 UTC, 0xdeadbad commented on src/actors/command.rs
> +                Some(a) => { let a = a.clone(); if a.len() == 0 {} else { nargs.push(a) } },
I made some changes. To mention, the entrypoint is hardcoded, I'll look for a better solution for this. Maybe using the user current shell or the user's shell itself.

2023-07-21 10:26 UTC, zifeo approved these changes
lgtm!

2023-07-21 10:27 UTC, merged