feat : recurse config file location
zifeo/whiz pull request #9
Opened 2022-12-24 14:44 UTC by afmika

2022-12-24 17:34 UTC, zifeo reviewed
Great PR, I added some suggestions/comments. Can you also add a test?

2022-12-24 17:34 UTC, zifeo commented on src/main.rs
> +    #[clap(short, long, default_value = "")]
Optional with None seems better than an empty string

2022-12-24 17:34 UTC, zifeo commented on src/main.rs
>      let mut config = match Config::from_file(&args.file) {
You can use directly the value here instead of having to make args mutable as the value is not used later

2022-12-24 20:05 UTC, afmika commented on src/main.rs
> +    #[clap(short, long, default_value = "")]
Sure, noted !

2022-12-27 07:54 UTC, afmika commented on src/utils.rs
> +        None => config_name_as_path.to_path_buf(),
My approach was to make this function error-free since specifying the configuration file on the cli is optional. If it fails on finding a configuration file, the name provided will be used as default value (for example `whiz.yaml`) the configuration file loader will then handle the error if it does not exist.

2022-12-27 11:54 UTC, Natoandro commented on src/utils.rs
> +        None => config_name_as_path.to_path_buf(),
I think tt would be more straightforward for the user to assume that if they have specified a path in a command argument, it will be used. So, the command argument would always take priority over the default search paths. If the given path does not exist, that should be an error. The recursive search should only run if the arg is missing.

2022-12-27 21:55 UTC, zifeo requested changes

2022-12-27 21:55 UTC, zifeo commented on src/main.rs
> +                    process::exit(1);
One more thing, we try to keep all exit code different, can you change the ones above?

2022-12-27 22:40 UTC, afmika commented on src/main.rs
> +                    process::exit(1);
Is anything that is not zero or equal to the exit codes that have already been used ok ? Or is there a pattern ?

2022-12-28 00:01 UTC, zifeo commented on src/main.rs
> +                    process::exit(1);
@afmika We use nonzero positive code, you can increment all the following ones (as whiz is not yet "released" to the wild, we can introduce some breaking changes).

2022-12-28 06:09 UTC, afmika commented on src/main.rs
> +                    process::exit(1);
Alright, got it !

2022-12-28 08:53 UTC, zifeo approved these changes
lgtm

2022-12-28 08:54 UTC, merged