Support run and task
zifeo/whiz pull request #98
Opened 2023-10-02 18:46 UTC by Yohe-Am

This PR fixes #83. 

I've decided to go with a straight forward solution and used an `Actor` that asks the `CommandActors` to tell it when they're finished. Once it has the go from all its targets, it exits the program.

In order to make the tool more CI friendly, I've also introduced a `--no-watch` flag that globally disables reloading triggered by fs watch events. I also recommend adding, in this PR or another, code that disables the `Console` actor when not needed and joins all the std pipes. The console makes little sense in a CI context.

2023-10-03 13:36 UTC, zifeo requested changes
Very well done! A few suggestions. For the the todo, would you mind create an issue or tackling them? Let's fix the CI & remove remove dead/commented code.

2023-10-03 13:36 UTC, zifeo commented on src/actors/command.rs
> +    no_watch: bool,
what about `watch: bool` with inverted meaning? that will simply the mental reasoning

2023-10-03 13:36 UTC, zifeo commented on src/actors/command.rs
> +                // TODO: consider introducing per command no_watch config
This is a great idea, the flag should override the task config from the `whiz.yml`

2023-10-03 13:36 UTC, zifeo commented on src/args.rs
> +    pub exit_after: bool,
I wonder a timeout should not also implemented: if exit is set, there must exist a timeout (or something like `exit_after: Option<u23)`). Let's say your have a faulty code or the internal subprocess watches some files.

2023-10-03 13:36 UTC, zifeo commented on src/args.rs
> +    pub no_watch: bool,
can we enforce watch be disabled if exist_after is used?

2023-10-03 14:22 UTC, zifeo commented
Also do not forget to include the flags in the readme.

2023-10-03 19:50 UTC, Yohe-Am commented on src/actors/command.rs
> +                // TODO: consider introducing per command no_watch config
Any ideas for what the API should be? 

An option is, if you're familiar with the tracing grates, you can alter the logging level of different crates/modules with syntax something like...`info,whiz=trace,serde=warn`. We can adopt something similar like...

`$ env WHIZ_WATCH="cmd1=false,cmd2=false" whiz`

...that customizes watching for each watch flag. 

We can also use command line flags like 
`$ whiz --task-watch "cmd1,false" --task-watch "cmd2=false"`

But now I'm wondering if this adds too many "knobs". How often will folks need to toggle watching per task for just for the CI. They can always disable it by commenting out the `watch` section of the task config.

2023-10-03 19:51 UTC, Yohe-Am commented on src/args.rs
> +    pub exit_after: bool,
A separate arg or should the current flag have dual support?

2023-10-03 19:56 UTC, Yohe-Am commented
Alright, I've resolved a few of the suggestions. They might bloat this PR but I have a few minor ideas for improvements in this direction:

- A keybinding in the console that'll trigger the `exit-after` behavior. This allows a scenario where a user can start in whiz without the flag, and they can  investigate the panels and such. If satisfied, they press the keybinding allowing whiz to complete when all the tasks are finished.  This is better than just using the flag alone since if the commands exit too quickly they might not give the user time to do proper investigations. The current implementation only needs slight modification to support this usecase.

- In the spirit of KISS, the implementation ignores any reloads that happens after the task has reported itself finished. The `exit-after` flag implies disabling file watching as well and I believe this approach won't surprise most users but maybe such behavior is desirable.

2023-10-05 10:20 UTC, zifeo approved these changes

2023-10-05 10:20 UTC, zifeo commented on src/args.rs
> +    pub exit_after: bool,
Let's leave this a follow-up improvement, we need some learnings/use-cases first.

2023-10-05 10:26 UTC, zifeo commented
@Yohe-Am That makes sense. I would keep this behaviour separated from `q`. Alternatively, flushing the log buffer ordered would maybe be even better if a debug is necessary or checking the run (as most of the CI will not show any log with the current implementation).

2023-10-05 19:15 UTC, Yohe-Am commented
After some investigation, the error was indeed elsewhere. I was led astray by the `Child::Killed` to `ExitStatus::Undetermined` mapping in `Child::exit_status`.  The main issue appears to be that the child is not always dead by the time the actor processes the `StdoutTerminated` event and the `ensure_stopped` therein call ends up pulling the plug. I suppose I'll have it wait for a while for the child to die, in the manner of `WaitStatus` before pulling the plug. I'm thinking, poll if the child is dead every 20 millis and kill it if a second has elapsed. Lemme see...

2023-10-05 19:58 UTC, Yohe-Am commented
Ayup, that seems to have fixed it. Seems to be working well now and ready to merge. I don't think the solution is a semantic violation, right? `StdoutTerminated` always correlates to death?

2023-10-06 12:14 UTC, zifeo commented on src/actors/command.rs
> +                // TODO: consider introducing per command no_watch config
I believe having just the "watch" as a flag on each task in the whiz.yml is enough

2023-10-06 12:20 UTC, zifeo commented
@Yohe-Am unsure of the last (quite complex :)) commit, I believe ensure_stopped should do the same behaviour. Do you see a diff?

2023-10-06 12:29 UTC, Yohe-Am commented
@zifeo `ensure_stopped` kills the child if it's still running. As it turns out, the child might still be running by the time `StdoutTerminated` is processed by the actor. That complex async bit's just giving slight breathing room (a second) for the command to complete naturally. Otherwise, this edge case robs us a chance of reading its actual error code.

2023-10-06 12:36 UTC, zifeo commented
@Yohe-Am would use `ensure_stop` somehow when the stdout terminated event is sent simplify that edge case? The CI seems still failing (maybe os specific).

2023-10-06 12:51 UTC, Yohe-Am commented
I suppose, to simplify the code, I can use the `wait_timeout` syscall to achieve the same behavior. It won't be async but I don't think that's a boon here. On the behavior this achieves though, I can't think of a simpler way of handling the edge case.

2023-10-06 12:54 UTC, Yohe-Am commented
> CI

yeah, I'm not sure why macOS `bash` is acting differently. hmm...

2023-10-06 13:15 UTC, Yohe-Am commented
Alright, I've pushed a change that simplify that async bit.

> CI, macOs

According to [this](https://stackoverflow.com/questions/12803631/osx-bash-sleep), it might be the time unit. on `sleep`. I've pushed a change that'll hopefully get it along.

2023-10-06 13:32 UTC, Yohe-Am commented
> windows

oof, right. Let me add a quick `cfg` case for the test

2023-10-07 21:17 UTC, Yohe-Am commented
Something appears to be wrong with Github, I'm unable to access the logs of the run.

![image](https://github.com/zifeo/whiz/assets/56622350/4044e052-b97f-4c42-abcc-3d122f56bb56)

I also tried accessing the raw longs and downloading the log archive but they just timeout after a while. I tried multiple browsers and I'm not behind a VPN either. The rest of the website appears functional as well. Hmm...

2023-10-07 21:19 UTC, Yohe-Am commented
Maybe starting another CI run might help?

2023-10-07 22:21 UTC, Yohe-Am commented
Turns out the `TIMEOUT` command on Windows only works in interactive shell sessions. According to [this](https://stackoverflow.com/questions/32307870/add-a-timeout-between-two-batch-command-lines-in-jenkins) and other discussions I've found, abusing the `PING` program as an alternative to `sleep` is common under `cmd` and that should hopefully fix that. 


Aand, after some consideration, seeing that a command as simple as `sleep` has quirked up all three platforms, I've just replaced it all with python invocations in the tests.

2023-10-19 11:29 UTC, zifeo approved these changes

2023-10-19 11:29 UTC, merged